### ISSUE TITLE
Thanks/Likes counters don't count correctly while hiding of own Thanks/Likes

### ISSUE THREAD

**Issue by SvePu** [Eldenroot/MyBB_Thank-you-like-plugin#144] opened 2017-02-03 16:56 UTC

**Comment by MyBB-Andro** [comment] 2017-02-03 17:03
Hi, it the setting is disabled for me but still i am having the issue. Should i try to recreate the issue after applying the patch?

My settings:
![thankyou_like](https://cloud.githubusercontent.com/assets/24277403/22600496/c06a8422-ea60-11e6-96fa-7330dfe217c2.png)

**Comment by SvePu** [comment] 2017-02-03 17:09
If Tapatalk issue still exists after installing patch, then it's 100% a tapatalk problem ;)
#143

**Comment by MyBB-Andro** [comment] 2017-02-03 17:12
Okay, i did updated the plugin and lang file by just overwriting the files. Now there is an error showing at top of every pages: `MyBB Internal: One or more warnings occurred. Please contact your administrator for assistance.`

What should i do?

**Comment by MyBB-Andro** [comment] 2017-02-03 17:15
@SvePu I replaced the language file only now, and it fixes the issue. No idea what's wrong with the plugin file code. It shown errors everywhere in the forum.

**Comment by SvePu** [comment] 2017-02-03 17:23
@MyBB-Andro - Could you send me a link to you board please?

**Comment by MyBB-Andro** [comment] 2017-02-03 17:29
It is fixed now.  Thank you very much mate, i actually copy pasted code in wrong place which caused the errors!

Instead of `4.04 percent of total 3953498` how about `4.04 percent of total likes`?

To match with default post and thread percentage count wordings.

**Comment by SvePu** [comment] 2017-02-03 17:38
@MyBB-Andro - The total counters counting all given or received thanks / likes at forum, why we shouldn't display it? ;) In any case we need the matching query for the percent calculation.

**Comment by MyBB-Andro** [comment] 2017-02-03 17:39
Got it, thank you again. Please mark this as fixed. :)

**Comment by Cu8eeeR** [comment] 2017-02-03 19:29
@SvePu - is it solved or not? I am a little bit confused now.

**Comment by SvePu** [comment] 2017-02-03 19:34
@Cu8eeeR - Not yet - Counter of received tyl in X post doesn't match

**Comment by lairdshaw** [comment] 2018-07-07 21:17
> Counter of received tyl in X posts in postbits doesn't match

@SvePu, do you mean that the count of posts for which likes have been received differs between that shown beside a user's name in thread view versus that shown in other views such as private messages?

That's the only problem I can see, and it seems to be caused by the lack in thankyoulike_postbit() of functionality equivalent to lines [1260](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/blob/3dfb875f41c80c2c1b8922af581f5502167c6a3c/inc/plugins/thankyoulike.php#L1260)-1274 in thankyoulike_postbit_udetails().

For me, the problem seems to be fixed by simply copy-and-pasting those lines into thankyoulike_postbit(), but better, I think, would be to abstract them into a function.

There is other duplicated functionality with respect to removing self-likes from counts: lines [973](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/blob/3dfb875f41c80c2c1b8922af581f5502167c6a3c/inc/plugins/thankyoulike.php#L973)-984 are doing the same job, but using different SQL, as lines [1253](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/blob/3dfb875f41c80c2c1b8922af581f5502167c6a3c/inc/plugins/thankyoulike.php#L1253)-1259 and as lines [1417](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/blob/3dfb875f41c80c2c1b8922af581f5502167c6a3c/inc/plugins/thankyoulike.php#L1417)-1423, and lines [1450](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/blob/3dfb875f41c80c2c1b8922af581f5502167c6a3c/inc/plugins/thankyoulike.php#L1450)-1456 are doing something very similar but for total liked post counts rather than for liked post counts of individual users. Perhaps we could abstract this functionality into its own function too?

**Comment by Eldenroot** [comment] 2018-07-08 10:04
I agree with you. Would be nice to have them in functions and maybe clean up these parts of code. I assigned you to this issue.

**Comment by SvePu** [comment] 2018-07-08 10:22
Agree @lairdshaw .. this plugin versions are further developments of an old plugin where are some stuff that we could combine into functions to call them on different places.

**Comment by Eldenroot** [comment] 2018-07-09 14:05
Fixed via https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/commit/20992cb5ac45492771494559d0c5810c5b5be994

**Closed by Eldenroot** 2018-07-09 14:05 UTC
Labels: bug, confirmed, fixed
